### PR TITLE
Unix line endings and gitattributes

### PR DESCRIPTION
**Pull request by ilya-kolpakov**
The line endings were inconsistent. This patch converts all text files in the repo to unix (LF) endings and introduces `.gitattributes` file that makes sure that new commits will always with be in unix format.

Setting `core.eol` property to `native` should be enough to convert LF to CLRF on Windows when checking out.

### CODE REVIEW

**Comment by ilya-kolpakov** [comment]
Didn't know the PR is tied to my master and not a specific commit.

**Comment by shakiba** [comment]
Thanks for your fix for new lines! I have already done several changes in my local branch so it is difficult to for me to merge it but I will integrated your fix in my next commit.

You are welcome to PR your example if you are interested (you don't need to include my name in license section).

**Comment by ilya-kolpakov** [comment]
Oh, I should've asked. I think it might be easier to convert everything again once you commit your local changes than to merge.

My changes are small and I could easily rebase manually on top of your latest version.

**Comment by shakiba** [comment]
I recommend adding Vec2.projectOn in the new example file so that you don't need to change the project source code.

**Comment by shakiba** [comment]
I merged your new-line fix. Thanks!

**Comment by shakiba** [comment]
@ilya-kolpakov I cherry-picked your tire example, and pushed it in a [new branch](https://github.com/shakiba/planck.js/tree/tire).

**Pull request closed without merging**
