### PR TITLE
Fix #144

### LINKED ISSUE #144: Type Error with Shape and BoxShape in TypeScript
So, I was getting started with some examples and creating a body with a fixture. The example [HeavyOnLight](https://github.com/shakiba/planck.js/blob/master/example/HeavyOnLight.js) has the code:
```
world.createDynamicBody(Vec2(0.0, 4.5)).createFixture(pl.Circle(0.5), 10.0);
```
since I am using TypeScript, my code is:

```
import pl from 'planck-js'
let world = new pl.World()
world.createBody().createFixture(pl.Box(100, 100))
```

TypeScript underlines the `pl.Box` part and says:
```
No overload matches this call.
  Overload 1 of 3, '(def: FixtureDef): Fixture', gave the following error.
    Argument of type 'BoxShape' is not assignable to parameter of type 'FixtureDef'.
      Type 'BoxShape' is missing the following properties from type 'FixtureDef': shape, userData, friction, restitution, and 5 more.
  Overload 2 of 3, '(shape: Shape, opt?: FixtureOpt | undefined): Fixture', gave the following error.
    Argument of type 'BoxShape' is not assignable to parameter of type 'Shape'.
      Type 'BoxShape' is missing the following properties from type 'Shape': m_type, m_radius, isValid, getRadius, and 7 more.
  Overload 3 of 3, '(shape: Shape, density?: number | undefined): Fixture', gave the following error.
    Argument of type 'BoxShape' is not assignable to parameter of type 'Shape'.
```

What am I doing wrong? It seems that BoxShape should be a child of Shape, but it isn't? How can I add a fixture to a body?

EDIT: this happens with `pl.Circle` too, the error is `Argument of type 'CircleShape' is not assignable to parameter of type 'Shape'.`

I am using `"planck-js": "^0.3.22"` and `"typescript": "^3.9.7"`

### PR DESCRIPTION
**Pull request by zOadT**
Extending classes in typings definition doesn't seem to work as on would expected, therefore we had to move back to the old Syntax of splitting a class in its static and non-static parts. (Thanks to @Doeke for the hint)

Note that the same problem applies to the typings of joints. I will create a separate issue for this.

### CODE REVIEW

**Comment by Doeke** [comment]
I usually don't write separate declaration files, so I still wonder why classes didn't work as expected. Have you tried `declare class` instead of `export class`?

**Comment by zOadT** [comment]
Good idea but does not seem to make a difference unfortunately. But I found out that the inheritance does not work because of the ambient function declarations. (So if we remove `export function BoxShape(...): BoxShape;` it would work. But you also would have to use the new keyword, so we do that as solution to our problem)
I guess this is a bug in Typescript, but maybe there is some strange explanation for this behaviour.

**Comment by shakiba** [comment]
What if you put function declaration after class? :)

**Comment by shakiba** [comment]
Thanks for you work by the way! :1st_place_medal:

**Comment by zOadT** [comment]
@shakiba Also thought about that, but sadly didn't work 😃

Moving function declarations into another file also just seem to create name conflicts. I will gladly try out other ideas, but currently it looks like we have to go with the current solution for now 🤔

**Comment by shakiba** [comment]
What about this?!
```
  declare class CircleShape extends Shape {
    //...
  }
  export function Circle(position: Vec2, radius?: number): CircleShape;
  export function Circle(radius?: number): CircleShape;
  export class Circle extends CircleShape { /* nothing here /* }
```

**Comment by zOadT** [comment]
Well, now TS behaves strangely 😄 The following does indeed resolve the code example in the issue:
```
export class CircleShape extends Shape {
  // These lines don't do any difference anymore
  // static TYPE: 'circle';
  // constructor(position: Vec2, radius?: number);
  // constructor(radius?: number);

  /** @internal */ m_type: 'circle';
  /** @internal */ m_p: Vec2;

  getCenter(): Vec2;
  getVertex(index?: number): Vec2;
  getVertexCount(index?: number): 1;
}
export function Circle(position: Vec2, radius?: number): CircleShape;
export function Circle(radius?: number): CircleShape;
export class Circle extends CircleShape { 
  static TYPE: 'circle'; // planck.Circle.TYPE === 'circle'

  test(): number; // all inherited properties exists but this gets irgnored!? Its like the other way around this time
}
```
BUT you can't create Circles with the new keyword anymore like `new planck.Circle(2)`. And we have two classes, again one for the instance properties and one for the static properties, which is pretty much the same as the current solution with an interface for instance properties and a dedicated object for static properties.
Therefore, I would still prefer the current solution, because it allows the `new` keyword and the segmentation in interface and object seems a bit cleaner to me. But maybe we can still find improvements to the above solution 😃

**Review by shakiba — APPROVED** [review]

**Pull request merged**
