### PR TITLE
more fixes in collision

### PR DESCRIPTION
**Pull request by zOadT**
Hey,

I think you have to call '.preorder' with `this.m_root` as argument because otherwise `it.next` directly returns `undefined` without running the loop even once.
(I will keep this PR as a draft for now because I found some other small things I want to fix 😄)

### CODE REVIEW

**Comment by zOadT** [comment]
@shakiba do you know how line 592/593 is supposed to be? Its probably either `var height1 = child1.height;` or `var height1 = this.m_nodes[child1.id].height;`.

**Comment by zOadT** [comment]
I think there is also a problem in `computeHeight` in DynamicTree 😅 :
```
/**
 * Compute the height of a sub-tree.
 */
public computeHeight(id) {
  var node;
  if (typeof id !== 'undefined') {
    node = this.m_nodes[id];
  } else {
    node = this.m_root;
  }

  // _ASSERT && common.assert(0 <= id && id < this.m_nodeCapacity);

  if (node.isLeaf()) {
    return 0;
  }

  var height1 = node.child1.computeHeight();
  var height2 = node.child2.computeHeight();
  return 1 + Math.max(height1, height2);
}
```
`node.child1` is a `TreeNode` and doesn't have a `computeHeight` method, so I think this should be `var height1 = this.computeHeight(node.child1.id)`.
But I would also suggest to directly take a `TreeNode` as argument instead of its id, this would avoid some redirections. Or is there a reason to pass the id and not the node itself?
And also: should an empty Tree return height `0` or `-1`? 😄

**Comment by shakiba** [comment]
Sorry for delay! I don't remember very well how this works! :thinking: But I guess it was supposed to be like this:
```
DynamicTree.prototype.computeHeight = function() {
  if (node.isLeaf()) {
    return 0;
  }
  var height1 = node.child1 ? node.child1.computeHeight() : 0;
  var height2 = node.child2 ? node.child2.computeHeight() : 0;
  return 1 + Math.max(height1, height2);
}
```
Here is original [Box2D file](https://github.com/behdad/box2d/blob/master/Box2D/Box2D/Collision/b2DynamicTree.cpp) if you are interested.
Thanks for fixing this! :1st_place_medal:

**Comment by shakiba** [comment]
Also I think I guess it is `var height1 = child1.height`.

**Comment by zOadT** [comment]
Thanks for referring to the original file. I see what happend now:
All methods in box2d receive a TreeNode reference by an integer pointing to an instance in `m_nodes`. (Also `m_root` and `child1` were just integers.) In planck.js almost all of these parameters got replaced by a direct 'javascript-object' reference, so the last commit just applies the same changes to `computeHeight`.

Note: Some methods like `moveProxy` and callbacks still use `id`. Maybe we can change this in the future once we got a TypeScript port (or change it back to use `id` everywhere again if it turns out to be somehow more performant)

**Comment by zOadT** [comment]
I think this PR is ready to be merged! Maybe you can take a quick look 🙂 (There's no rush)

**Comment by shakiba** [comment]
Sorry my bad, I didn't notice other methods still take id instead of reference, so I think it is safer to leave `computeHeight()` parameter as id for this PR. :man_facepalming: 
I agree it is worth it to see if we can replace node id with reference in the entire project.

Looks great to me otherwise, please feel free to merge it.

**Pull request merged**
